#!/bin/bash
# Delete old files
rm /tmp/w3-checkresult*.html

IFS=$'\n'
for file in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
do
	tempfilenumber=$RANDOM
	curl -F uploaded_file=@"$file" http://validator.w3.org/check>/tmp/w3-checkresult$tempfilenumber.html
	gnome-open /tmp/w3-checkresult$tempfilenumber.html
done
